### ISSUE TITLE
.json seems to return type str instead of a json object

### ISSUE THREAD

**Issue by EthanHicks1** [luissilva1044894/Pyrez#10]
So for example:

```python
info = paladinsAPI.getPlayer(player_name)
data = info.json
print(type(data))
```

the print statement returns that it is of type string 

> <class 'str'>

**Comment by luissilva1044894** [comment]
@EthanHicks1 Yeah, [**Object.json**](https://github.com/luissilva1044894/Pyrez/blob/d92ab3e88bc67961e0d341fa0013dd81157c7c67/pyrez/models.py#L6) will return **str**. I'll change it and just return as String when using ```str(object.json)``` aka ```__str__()```

As I said, you can just use **Object.property**. **Object.json** was **str** why ```getPlayer()``` return a class containing all fields.

```py
info = paladinsAPI.getPlayer(player_name)

print(type(info))
<class 'pyrez.models.PlayerPaladins'>

print(dir(info))
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__',
'__format__', '__ge__', '__getattribute__', '__gt__', '__hash__',
'__init__', '__init_subclass__', '__le__', '__lt__', '__module__',
'__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__',
'__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__',
'accountLevel', 'activePlayerId', 'createdDatetime', 'getWinratio', 'hasRetMsg',
'hoursPlayed', 'hzGamerTag', 'hzPlayerName', 'json', 'lastLoginDatetime', 'leaves',
'losses', 'mergedPlayers', 'platform', 'playedGods', 'playerId', 'playerName',
'playerRank', 'playerRankController', 'playerRankKeyboard', 'playerRegion',
'playerStatusMessage', 'rankedConquest', 'rankedController', 'rankedKeyboard',
'retMsg', 'teamId', 'teamName', 'totalAchievements', 'totalXP', 'wins']
```

**Comment by EthanHicks1** [comment]
While we are on the subject of json data:

```python
print(type(paladinsAPI.getPlayerStatus(player_id)))
data = paladinsAPI.getPlayerStatus(player_id)
print(data)
```

prints:
```
<class 'pyrez.models.PlayerStatus'>
{'Match': 0, 'match_queue_id': 0, 'personal_status_message': None, 'ret_msg': None, 'status': 0, 'status_string': 'Offline'}
```
Which as far as I can tell has no way to get the data inside of it unless you loop through it. I just converted it to json myself. This is hardly going to be used though so I don't know if you need to change anything. Just wanted to mention it.

**Comment by luissilva1044894** [comment]
@EthanHicks1 Not sure if I got it. What's the problem? How to access it? 

If you prefer to call .json and convert manually, just copy/paste it to models.py and convert whatever you need
```py
class BaseAPIResponse:
    def __init__(self, **kwargs):
        self.json = kwargs if kwargs is not None else None
    def __str__(self):
        return str(self.json) if self.json is not None else None
```
Using: ``` print(info)``` Note: print(info) is exactly the same one that str(info)

Will return the **kwargs as string (Without [], almost all Paladins endpoints return []):
```{'ActivePlayerId': 572693, 'Created_Datetime': '3/31/2016 7:57:47 PM', 'HoursPlayed': 1104, 'Id': 572693, 'Last_Login_Datetime': '3/1/2019 3:01:58 PM', 'Leaves': 24, 'Level': 480, 'Losses': 2167, 'MasteryLevel': 39, 'MergedPlayers': None, 'Name': 'FeyRazzle', 'Personal_Status_Message': '', 'Platform': 'Steam', 'RankedConquest': {'Leaves': 0, 'Losses': 0, 'Name': 'Conquest', 'Points': 0, 'PrevRank': 0, 'Rank': 0, 'Season': 0, 'Tier': 0, 'Trend': 0, 'Wins': 0, 'player_id': None, 'ret_msg': None}, 'RankedController': {'Leaves': 0, 'Losses': 0, 'Name': 'Ranked Controller', 'Points': 0, 'PrevRank': 0, 'Rank': 0, 'Season': 0, 'Tier': 0, 'Trend': 0, 'Wins': 0, 'player_id': None, 'ret_msg': None}, 'RankedKBM': {'Leaves': 0, 'Losses': 40, 'Name': 'Ranked KBM', 'Points': 43, 'PrevRank': 264, 'Rank': 264, 'Season': 3, 'Tier': 26, 'Trend': 0, 'Wins': 52, 'player_id': None, 'ret_msg': None}, 'Region': 'Europe', 'TeamId': 0, 'Team_Name': '', 'Tier_Conquest': 0, 'Tier_RankedController': 0, 'Tier_RankedKBM': 26, 'Total_Achievements': 56, 'Total_Worshippers': 620734339, 'Wins': 3380, 'hz_gamer_tag': None, 'hz_player_name': 'FeyRazzle', 'ret_msg': None}```


dir(Object) tells you all things that you can use. Some calls:
```py
info.playerRankKeyboard.getWinratio() #pyrez.models.BaseRanked
info.playerRankKeyboard.wins #pyrez.models.BaseRanked
info.playerRankKeyboard.currentRank #pyrez.models.BaseRanked
info.wins #int
info.playerName #str/None
```

**Comment by EthanHicks1** [comment]
Cool. I thought since the autocomplete of the compiler did not show options like `dir()` then there was not an easy way to get the data.

**Comment by luissilva1044894** [comment]
Now, all data can be accessed directly by json:

#### Usage:
```py
data = paladinsAPI.getPlayer("FeyRazzle")
print(data.json["ActivePlayerId"])
print(data.json["Id"])
print(data.json["Name"])
```

**Comment by luissilva1044894** [comment]
Now, all data can be accessed directly by json:

#### Usage:
```py
data = paladinsAPI.getPlayer("FeyRazzle")
print(data.json["ActivePlayerId"])
print(data.json["Id"])
print(data.json["Name"])
```

Note: Just classes that extends [**pyrez.models.APIResponse**](https://github.com/luissilva1044894/Pyrez/blob/b3cd99e014d925de9b0ad8d1b836839c0ce98cb6/pyrez/models.py#L9) has Object.json

**Comment by luissilva1044894** [comment]
Also, [`JSON data can be accessed by index keys`](https://github.com/luissilva1044894/Pyrez/commit/16fd6c5d1392c6f25c65dd7097663b8983c1ecfc):

#### Usage:
```py
data = paladinsAPI.getPlayer("FeyRazzle")
print(data["ActivePlayerId"])
print(data["Id"])
print(data["Name"])
```
