### ISSUE TITLE
Docs directory missing ?

### ISSUE THREAD

**Issue by shaklev** [luissilva1044894/Pyrez#2]
> Detailed documentation is in the "docs" directory.

I can't seem to find the docs dir ( it would be really useful , to check which functions are available )

**Comment by luissilva1044894** [comment]
@shaklev Sorry... I was "out". Sadly, but the docs is really missing. I'll try to provide it this week!

**Comment by shaklev** [comment]
@luissilva1044894 also i won't open another issue , but is there something wrong with the code ? In the example: `paladinsAPI = PaladinsAPI (devId=1004, authKey="23DF3C7E9BD14D84BF892AD206B6755C")
` there is a space between the class name and the parentheses ( i find that in the other parts of the code as well )

**Comment by luissilva1044894** [comment]
I got issues when trying to update on pip, so I just was coding / fixing before submit a new update (why you can't use the same one version on Pip, so "random" updates isn't good). This repo was "dropped" 2 months ago, but I'll back to code it.


Thanks for your pull request! I read your comment, but wasn't online to reply.

What is the problem with spaces? I was coding like I code in C#, it's better to read / code. Also, I know that somethings are CamelCase when could be lowercase...

And I'm starting to write the Wiki. I'm not a English native, so it'll spend some time but I'll try to do it so fast I can!

**Comment by shaklev** [comment]
It's good to have the newest version of the project updated on github ( so that other developers can help upgrading the project, this way , you'll have to merge the changes done on github with the ones you have already deployed on pypi ).

The spaces are not an issue in python as well ( bus usually there aren't spaces between ). About the CamelCase or using `func_name` , thats just developers preference.

For the Wiki i could help you if you have some issues , feel free to write me.

**Comment by luissilva1044894** [comment]
The github version was the lastest version. But I was coding somethings offline and didn't updated. 

I'm trying to learning how to use the Read the Docs, I think that it can be better than write the Wiki.

Whatever, I'm writing some comments that can be read using `help(object)` in Python.

**Comment by luissilva1044894** [comment]
Released a "beta" [doc](https://pyrez.readthedocs.io/en/1.0.1/).
